name: Customer API

on:
  repository_dispatch:
    types: [customer]

jobs:
  Add_customer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Edit file
        env:
          NUMBER: ${{ github.event.client_payload.number }}
        run: |
          # edit file
          echo "$NUMBER" >> wait_list.txt
      
      # commit file
      - uses: stefanzweifel/git-auto-commit-action@v5