name: Reception API

on:
  repository_dispatch:
    types: [reception]

jobs:
  Remove_customer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Edit file
        env:
          NUMBER: ${{ github.event.client_payload.number }}
        run: |
          # edit file
          NUMBER="${NUMBER},"
          sed "s/$NUMBER//g" wait_list.txt > wait_list.txt
      
      # commit file
      - uses: stefanzweifel/git-auto-commit-action@v5